baseURL = "https://www.insightbotics.com"
languageCode = "en-us"
title = "Insightbotics"
theme = "hugo-saasify-theme"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
enableGitInfo = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/logo.svg"
  googleAnalytics = "G-XXXXXXXXXX"

  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"

    [params.header.logo]
      src = "/images/logo.svg"

    [params.header.buttons]
      [params.header.buttons.signIn]
        text = "Linkedin"
        url = "https://www.linkedin.com/company/insightbotics"
      [params.header.buttons.getStarted]
        text = "Get Started"
        url = "https://movie-learner.vercel.app/"

  [params.cta]
    enable = true
    title = "Ready to Get Started?"
    description = "Join companies using our platform"
    [params.cta.primary_button]
      text = "Start Translation"
      url = "https://www.insightbotics.com"
    [params.cta.secondary_button]
      text = "Start Learning"
      url = "https://movie-learner.vercel.app/"

  [params.social]
    linkedin = "https://www.linkedin.com/company/insightbotics"
    twitter = "https://x.com/insightbotics"
    github = "https://github.com/insightbotics"
    hr = "https://www.104.com.tw/company/1a2x6bms5y?jobsource=google"

[menu]
  [[menu.main]]
    name = "Features"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "SpeakSync｜Instant Translation", url = "/features/Real-Time-Speech-Translation/" },
        { name = "StudySync｜Fast Learning", url = "/features/Fast-Learning/" },
        { name = "DataSync｜AI Business Analytics", url = "/features/AI-Business-Analytics/" },
        { name = "HeartSync｜Wearable FetalECG", url = "/features/Wearable-FetalECG/" }
      ]
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Careers"
    url = "/careers"
    weight = 4
  [[menu.main]]
    name = "Company"
    url = "/company"
    weight = 5
